# Generated by Django 2.1.4 on 2019-02-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0004_auto_20190203_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Postings',
        ),
    ]
