# Generated by Django 2.1.4 on 2019-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0006_adminlogin_createagent_job_postings_success_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=50)),
                ('Suggession', models.CharField(max_length=100)),
            ],
        ),
    ]
