# Generated by Django 2.1.4 on 2019-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0008_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('agent_id', models.IntegerField()),
                ('Agent_Name', models.CharField(max_length=30)),
            ],
        ),
    ]
