# Generated by Django 2.1.4 on 2019-02-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0011_defence_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30)),
                ('case_details', models.CharField(max_length=30)),
                ('doc', models.DateField()),
                ('evidence', models.CharField(max_length=30)),
            ],
        ),
    ]
